# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: daan-scholten
description: Daan Scholten - Producer - Sound Engineer
author:
  name: Anoesj Sadraee
  email: anoesjsadraee@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

sass:
  sass_dir: app/_scss

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false
permalink: /blog/:title/
# /:categories
# /:year

collections:
  projects:
    output: false
  clients:
    output: false
  pages:
    output: true
    permalink: /:path/

prose:
  rooturl: 'app'
  relativeLinks: 'http://anoesjsadraee.com/Prose-relative-links/daan-scholten.jsonp'
  siteurl: 'http://www.daanscholten.nl/'
  media: 'app/resources/img'
  ignore:
    - index.md
    - _config.yml
    - app/_layouts
    - app/_includes
    - app/_plugins
    - app/_bower_components
    - app/_scss
    - app/blog
    - app/contact
    - app/resources/data
    - app/resources/js
    - app/resources/css
    - app/fonts
    - app/*.*
    - app/CNAME
    - app/templates
  metadata:
    app/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Titel:"
          placeholder: "Titel"
          value: "Titel"
      - name: "date"
        field:
          element: "text"
          label: "Datum:"
          placeholder: "yyyy-mm-dd uu:mm"
          value: "2015-01-01 13:00"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Tags:"
          placeholder: "Selecteer tags"
          alterable: true
          options:
            - name: "studio"
              value: "studio"
            - name: "live"
              value: "live"
            - name: "EP"
              value: "EP"
            - name: "album"
              value: "album"
      - name: "published"
        field:
          element: "checkbox"
          label: "Nu publiceren?"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Wijzig permalink:"
          placeholder: "/blog/hoi-ik-ben-daan/"
          value: ""
    app/_projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "title"
        field:
          element: "text"
          label: "Titel:"
          placeholder: "Titel"
          value: "Titel"
      - name: "date"
        field:
          element: "text"
          label: "Datum:"
          placeholder: "yyyy-mm-dd uu:mm"
          value: "2015-01-01 13:00"
      - name: "target"
        field:
          element: "text"
          label: "Doellink:"
          placeholder: "/blog/voorbeeld-linkje/"
      - name: "published"
        field:
          element: "checkbox"
          label: "Nu publiceren?"
          value: true
    app/_clients:
      - name: "layout"
        field:
          element: "hidden"
          value: "client"
      - name: "title"
        field:
          element: "text"
          label: "Klantnaam:"
          placeholder: "Klantnaam"
          value: "Klantnaam"
      - name: "target"
        field:
          element: "text"
          label: "Doellink:"
          placeholder: "http://www.metropool.nl/"
      - name: "published"
        field:
          element: "checkbox"
          label: "Nu publiceren?"
          value: true
    app/_pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Titel:"
          placeholder: "Titel"
          value: "Titel"
      - name: "published"
        field:
          element: "checkbox"
          label: "Nu publiceren?"
          value: true
