# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: daan-scholten
description: Daan Scholten - Producer - Sound Engineer
author:
  name: Anoesj Sadraee
  email: anoesjsadraee@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

sass:
  sass_dir: app/_scss

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false
permalink: /blog/:title/
# /:categories
# /:year

collections:
  - projects

prose:
  rooturl: 'app'
  relativeLinks: 'links.jsonp'
  siteurl: 'http://www.daanscholten.nl/'
  media: 'app/resources/img'
  ignore:
    - index.md
    - _config.yml
    - app/_layouts
    - app/_includes
    - app/_plugins
    - app/_bower_components
    - app/_scss
    - app/resources/css
    - app/resources/js
    - app/fonts
  metadata:
    app/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - date: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categorieën"
          placeholder: "Selecteer één of meerdere categorieën"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "published"
        field:
          element: "checkbox"
          label: "Nu publiceren?"
          value: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
